[workspace]
members = ["./snowchains_core"]

[package]
name = "snowchains"
version = "0.3.3"
edition = "2018"
authors = ["Ryo Yamashita <qryxip@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Tools for online programming contests"
repository = "https://github.com/qryxip/snowchains"
documentation = "https://docs.rs/snowchains"
readme = "README.md"
keywords = ["competitive", "cli", "windows"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.31"
atty = "0.2.14"
cookie_store = "0.12.0"
dhall = "0.5.3"
dirs = "3.0.1"
heck = "0.3.1"
indexmap = { version = "1.4.0", features = ["serde-1"] }
indicatif = "0.15.0"
indoc = "0.3.6"
itertools = "0.9.0"
maplit = "1.0.2"
reqwest = { version = "0.10.6", default-features = false, features = ["blocking"] }
rpassword = "4.0.5"
rprompt = "1.0.5"
serde = { version = "1.0.114", features = ["derive"] }
serde_dhall = "0.5.3"
serde_json = "1.0.56"
serde_yaml = "0.8.13"
shell-escape = "0.1.5"
snowchains_core = { version = "0.0.0", path = "./snowchains_core" }
structopt = "0.3.15"
strum = { version = "0.18.0", features = ["derive"] }
tempfile = "3.1.0"
termcolor = "1.1.0"
url = { version = "2.1.1", features = ["serde"] }

[dev-dependencies]
difference = "2.0.0"
pretty_assertions = "0.6.1"
retry = "1.0.0"
