[package]
name = "snowchains"
version = "0.3.3"
edition = "2018"
authors = ["Ryo Yamashita <qryxip@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Tools for online programming contests"
repository = "https://github.com/qryxip/snowchains"
documentation = "https://docs.rs/snowchains"
readme = "README.md"
keywords = ["windows", "cli"]
categories = ["command-line-utilities"]

[badges]
# https://github.com/srijs/deps.rs/pull/33
# codecov = { repository = "qryxip/snowchains" }

[workspace]

[dependencies]
atty = "0.2.14"
base64 = "0.12.0"
chrono = { version = "0.4.11", features = ["serde"] }
combine = "4.0.1"
cookie012 = { package = "cookie", version = "0.12.0" }
cookie_store = "0.10.0"
crossbeam-utils = "0.7.2"
ctrlc = "3.1.3"
derivative = "2.1.1"
derive-new = "0.5.8"
derive_more = "0.99.5"
diff = "0.1.12"
dirs = "2.0.2"
dunce = "1.0.0"
ego-tree = "0.6.2"
either = "1.5.3"
failure = "0.1.7"
fs2 = "0.4.3"
futures01 = "0.1.29"
heck = "0.3.1"
hex = "0.4.0"
http01 = { package = "http", version = "0.1.21" }
if_chain = "1.0.0"
indexmap = { version = "1.3.1", features = ["serde-1"] }
itertools = "0.9.0"
maplit = "1.0.2"
matches = "0.1.8"
mime = "0.3.16"
num-traits = "0.2.11"
num_cpus = "1.13.0"
once_cell = "1.3.1"
prettytable-rs = { version = "0.8.0", default-features = false }
rand = "0.7.3"
rayon = "1.3.0"
ref-cast = "1.0.1"
regex = "1.3.7"
reqwest = { version = "0.9.24", default-features = false, features = ["rustls-tls"] }
robots_txt = "0.7.0"
rpassword = "4.0.5"
scraper = "0.11.0"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
serde_urlencoded = "0.6.1"
serde_yaml = "0.8.11"
sha2 = "0.8.1"
smallvec = "1.3.0"
snowchains_proc_macros = { path = "./proc_macros", version = "0.2.0" }
stable_deref_trait = "1.1.1"
static_assertions = "1.1.0"
structopt = "0.3.13"
strum = { version = "0.18.0", features = ["derive"] }
take_mut = "0.2.2"
termcolor = "1.1.0"
tokio-process = "0.2.4"
tokio01 = { package = "tokio", version = "0.1.22" }
toml = "0.5.6"
toml_edit = "0.1.5"
unicode-width = "0.1.7"
url = "2.1.1"
url1 = { package = "url", version = "1.7.2" }
webbrowser = "0.5.2"
which = { version = "3.1.1", features = ["failure"] }
yaml-rust = "0.4.3"
zip = "0.5.5"

[target.'cfg(not(windows))'.dependencies]
term_size = "0.3.1"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.8"
winapi-util = "0.1.4"

[target.'cfg(unix)'.dependencies]
signal-hook = { version = "0.1.13", features = ["tokio-support"] }

[dev-dependencies]
difference = "2.0.0"
http = "0.2.1"
md5 = "0.7.0"
pretty_assertions = "0.6.1"
retry = "1.0.0"
tempdir = "0.3.7"
tokio = { version = "0.2.18", features = ["macros", "rt-core", "rt-threaded", "sync"] }
warp = "0.2.2"
